name: pitaka
description: Paytaca mobile wallet app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.0+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  qr_flutter: ^3.0.1
  flutter_barcode_scanner: ^0.1.5+1
  local_auth: ^0.4.0+1
  flutter_sodium: ^0.0.9
  hex: ^0.1.2
  fluro: ^1.4.0
  after_layout: ^1.0.7
  intl: ^0.15.7
  flutter_markdown: ^0.2.0
  flutter_masked_text: ^0.8.0
  back_button_interceptor: ^2.0.0
  dio: ^2.0.7
  dio_flutter_transformer: ^2.0.6
  path_provider: ^0.5.0+1
  shared_preferences: ^0.5.1+1
  swipedetector: ^1.2.0
  crypto: ^2.0.6
  flutter_datetime_picker: ^1.1.6
  permission_handler: ^3.0.0
  sqflite: ^1.1.5
  connectivity: ^0.4.3+5
  flutter_secure_storage: ^3.2.1+1
  archive: ^2.0.8
  passcode_screen:
  screen_state: ^0.1.1
  http: ^0.12.0+2
  uuid: ^2.0.2
  url_launcher: ^5.2.7
  flutter_udid: ^1.0.1
  overlay_support: ^1.0.3
  image_picker: ^0.6.2+2
  firebase_dynamic_links: ^0.5.0+8
  firebase_messaging: ^6.0.3

  easy_dialog:
    git:
      url: git@github.com:paytaca/easy_dialog.git
      ref: master

  virtual_keyboard:
    git:
      url: git@github.com:paytaca/virtual_keyboard.git
      ref: master

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icon/icon.png
    - assets/images/background1.png
    - assets/images/loading.gif
    - assets/images/default_profile_pic.png
    - assets/texts/terms_and_conditions.txt

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
