#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=P:\src\flutter"
export "FLUTTER_APPLICATION_PATH=P:\AndroidStudioProjects\pitaka2\pitaka"
export "FLUTTER_TARGET=lib\main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build\ios"
export "FLUTTER_FRAMEWORK_DIR=P:\src\flutter\bin\cache\artifacts\engine\ios"
export "FLUTTER_ROOT=/home/annagat/flutter"
export "FLUTTER_APPLICATION_PATH=/home/annagat/development/projects/paytaca/pitaka"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_FRAMEWORK_DIR=/home/annagat/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
